aoc_fruit_detector:
  ros__parameters:
    min_depth: 0.1
    max_depth: 15.0
    constant_depth_value: 0.5
    fruit_type: "strawberry" # currently supported for "strawberry" or "tomato"
    pose3d_frame: 'zed_left_camera_optical_frame'
    pose3d_tf: False # True: if optical frame to camera frame pose transformation required, False: no tf require (ps: false for frame_id in camera_info is optical frame) 
    verbose: [True, True, True, True, True] # To draw [centroid, bbox, mask, coordinate frames, text] annotations on image
    pub_verbose: True # To publish annotated image
    pub_markers: True # To publish RViz markers
    use_ros: True # To subscribe RGBD data and publish output from/on ROS2 framework
