name: 'devcontainer CI' 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: lcas
    strategy:
      matrix:
        include:
          - configFile: .devcontainer/cuda-opengl/devcontainer.json
            imageTag: cuda-opengl-hri
    steps:
      - name: Node Js
        uses: actions/setup-node@v4
        with:
          node-version: "^16.13.0 || >=18.0.0"
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: What
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: "image name from repo name"
        id: docker_image_name
        run: echo "docker_image=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' |sed 's/[^0-9,a-z,A-Z,=,_,\/]/-/g' >>${GITHUB_OUTPUT}

      - name: Build and run dev container task
        if: ${{ github.event_name == 'pull_request' }}
        uses: devcontainers/ci@v0.3
        with:
          imageName: lcas.lincoln.ac.uk/devcontainer/${{ steps.docker_image_name.outputs.docker_image }}
          push: never
          configFile: ${{ matrix.configFile }}
          imageTag: ${{ matrix.imageTag }}-pr-ci
